### ISSUE TITLE
Get/Set configuration parameter -> memry access error

### ISSUE THREAD

**Issue by christophk86** [3dtof/voxelsdk#52] opened 2015-12-27 17:08 UTC
Hi everybody,

I want to read and write configuration parameters without using the configuration files.
I use the "get" and "getParam" functions but both functions cause to a memory access error.

My debug results are:
The function "_parameters.find(name)" raises the memory access error.

ParameterPtr param = depthCamera->getParam("unambiguous_range");
memory access error
const ParameterPtr DepthCamera::getParam(const String &name) const
{
  auto p = _parameters.find(name); // function raises the memory access error
...
}

What is wrong with this function or its usage?
Could you please help me to solve this quite strange error.

Thank you in advance.
Chris

**Comment by hlprasu** [comment] 2015-12-27 18:08
Hi Chris,

I do not see anything wrong with this in particular. It seems that error
must be due to something else.

Could you please a short program which reproduces this error?

Regards,
Prasad


On 27 December 2015 at 22:38, christophk86 <notifications@github.com> wrote:

> Hi everybody,
>
> I want to read and write configuration parameters without using the
> configuration files.
> I use the "get" and "getParam" functions but both functions cause to a
> memory access error.
>
> My debug results are:
> The function "_parameters.find(name)" raises the memory access error.
>
> ParameterPtr param = depthCamera->getParam("unambiguous_range");
> memory access error
> const ParameterPtr DepthCamera::getParam(const String &name) const
> {
> auto p = _parameters.find(name); // function raises the memory access error
> ...
> }
>
> What is wrong with this function or its usage?
> Could you please help me to solve this quite strange error.
>
> Thank you in advance.
> Chris
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/3dtof/voxelsdk/issues/52>.
>



-- 
~ Prasad Bhat

**Comment by gadiyar** [comment] 2017-01-04 07:57
Closing - please reopen if this is still an issue.

**Closed by gadiyar** 2017-01-04 07:57 UTC
